- name: Update all packages on system
  ansible.builtin.dnf:
    name: '*'
    state: present

- name: Install basic packages for production readiness
  ansible.builtin.dnf:
    name:
      - chrony
      - logrotate
      - firewalld
      - python3-firewall
    state: present

- name: Install SELinux dependencies
  ansible.builtin.dnf:
    name: python3-libsemanage
    state: present
  when: ansible_distribution_major_version | int >= 31

- name: Install SELinux dependencies (older versions)
  ansible.builtin.dnf:
    name: libsemanage-python
    state: present
  when: ansible_distribution_major_version | int <= 30

- name: Enable and start chrony
  ansible.builtin.systemd:
    name: chronyd
    state: started
    enabled: true

- name: Enable and start firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: true

- name: Update firewalld to allow DNS TCP requests
  ansible.posix.firewalld:
    port: 53/tcp
    permanent: true
    state: enabled

- name: Update firewalld to allow DNS UDP requests
  ansible.posix.firewalld:
    port: 53/udp
    permanent: true
    state: enabled

- name: Reload firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded
