---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    tmpfs:
      - /tmp
provisioner:
  name: ansible
  config_options:
    defaults:
      allow_broken_conditionals: true
verifier:
  name: ansible
