---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      allow_broken_conditionals: true
      roles_path: ../../
verifier:
  name: ansible
