---
- name: Verify
  hosts: all
  tasks:

    - name: Check if systemd is running
      stat:
        path: /run/systemd/system
      register: systemd_running

    - name: Check BIND service
      ansible.builtin.service:
        name: "{{ 'bind9' if ansible_os_family == 'Debian' else 'named' }}"
        state: started
      register: bind_service_status
      when:
        - ansible_service_mgr == 'systemd'
        - systemd_running.stat.exists

    - name: Assert service is running
      ansible.builtin.assert:
        that: bind_service_status.state == 'started'
      when:
        - ansible_service_mgr == 'systemd'
        - systemd_running.stat.exists

    - name: Check DNS resolution
      ansible.builtin.command: dig @localhost www.opennic.org
      register: bind_dig_result
      failed_when: bind_dig_result.rc != 0
      changed_when: false

    - name: Assert DNS works
      ansible.builtin.assert:
        that: bind_dig_result.rc == 0
