# SPDX-License-Identifier: Apache-2.0
- name: Restart trust_dns
  ansible.builtin.systemd:
    name: trust-dns
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
#  handlers file for trust_dns
