- name: Update all packages on system
  ansible.builtin.apt:
    name: '*'
    state: present
    force_apt_get: true
    update_cache: true

- name: Install basic packages for production readiness
  ansible.builtin.apt:
    name:
      - ntp
      - logrotate
      - ufw
    state: present
    force_apt_get: true

- name: Enable and start NTP
  ansible.builtin.systemd:
    name: ntp
    state: started
    enabled: true

- name: Enable and start ufw
  ansible.builtin.systemd:
    name: ufw
    state: started
    enabled: true

- name: Ensure SSH is allowed
  community.general.ufw:
    rule: allow
    name: OpenSSH

- name: Update ufw to allow DNS TCP requests
  community.general.ufw:
    rule: allow
    port: '53'
    proto: tcp

- name: Update ufw to allow DNS UDP requests
  community.general.ufw:
    rule: allow
    port: '53'
    proto: udp

- name: Reload ufw
  community.general.ufw:
    state: reloaded
