# SPDX-License-Identifier: Apache-2.0
- name: Download Rust installer
  ansible.builtin.get_uri:
    url: https://sh.rustup.rs
    dest: /tmp/rustup.sh
    mode: '0755'
  when: ansible_os_family == 'Debian'

- name: Install Rust
  ansible.builtin.shell: |
    set -o pipefail
    /tmp/rustup.sh -y
  args:
    creates: ~/.cargo/bin/rustc
  when: ansible_os_family == 'Debian'

- name: Add Rust to PATH
  ansible.builtin.lineinfile:
    path: ~/.bashrc
    line: 'export PATH="$HOME/.cargo/bin:$PATH"'
  when: ansible_os_family == 'Debian'

- name: Install trust-dns-server
  ansible.builtin.command: ~/.cargo/bin/cargo install trust-dns-server
  args:
    creates: ~/.cargo/bin/trust-dns-server
  when: ansible_os_family == 'Debian'

- name: Create trust-dns config directory
  ansible.builtin.file:
    path: /etc/trust-dns
    state: directory
    mode: "0755"

- name: Deploy trust-dns config
  ansible.builtin.template:
    src: server.toml.j2
    dest: /etc/trust-dns/server.toml
    mode: "0644"
  notify: restart trust_dns

- name: Create systemd service file
  ansible.builtin.template:
    src: trust-dns.service.j2
    dest: /etc/systemd/system/trust-dns.service
    mode: "0644"
  notify: reload systemd

- name: Enable and start trust-dns
  ansible.builtin.systemd:
    name: trust-dns
    state: started
    enabled: true
  when: ansible_os_family == 'Debian'
#  tasks file for trust_dns
